apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    user: postgres
    database: dataml_pro
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1000
    isDefault: true
    uid: dataml-postgres
    editable: true



