"""Core data processing, ML pipeline, and visualization modules."""

from core.cleaner import CleaningReport, clean_dataframe, detect_outliers_iqr
from core.feature_engineering import (
    FeatureEngineeringResult,
    engineer_features,
    preview_encoding_plan,
)
from core.loader import (
    DatasetSummary,
    LoadResult,
    LoaderError,
    load_csv,
    load_csv_with_fallback_encoding,
)
from core.model_training import (
    TrainingResult,
    save_training_artifacts,
    train_all_models,
)
from core.predictor import (
    PredictionConfig,
    PredictionResult,
    build_prediction_config,
    get_input_feature_columns,
    load_prediction_config,
    predict_dataframe,
    predict_from_features,
    predict_test_split,
    transform_rows_for_prediction,
)
from core.preprocessor import (
    PreprocessResult,
    build_model_pipeline,
    build_preprocessor,
    model_requires_scaling,
    preprocess_dataset,
    preprocess_from_feature_result,
    recommend_scaler,
)
from core.visualizer import (
    build_eda_figures,
    plot_correlation_heatmap,
    plot_histogram,
    plot_missing_bar,
    plot_missing_heatmap,
    plot_scatter,
)
from core.utils import (
    ColumnGroups,
    ProblemType,
    classify_columns,
    detect_problem_type,
    get_logger,
    setup_logging,
    suggest_target_column,
    to_csv_bytes,
)

__all__ = [
    "DatasetSummary",
    "LoadResult",
    "LoaderError",
    "load_csv",
    "load_csv_with_fallback_encoding",
    "CleaningReport",
    "clean_dataframe",
    "detect_outliers_iqr",
    "FeatureEngineeringResult",
    "engineer_features",
    "preview_encoding_plan",
    "PreprocessResult",
    "build_model_pipeline",
    "build_preprocessor",
    "model_requires_scaling",
    "preprocess_dataset",
    "preprocess_from_feature_result",
    "recommend_scaler",
    "build_eda_figures",
    "plot_correlation_heatmap",
    "plot_histogram",
    "plot_missing_bar",
    "plot_missing_heatmap",
    "plot_scatter",
    "TrainingResult",
    "save_training_artifacts",
    "train_all_models",
    "PredictionConfig",
    "PredictionResult",
    "build_prediction_config",
    "get_input_feature_columns",
    "load_prediction_config",
    "predict_dataframe",
    "predict_from_features",
    "predict_test_split",
    "transform_rows_for_prediction",
    "ColumnGroups",
    "ProblemType",
    "classify_columns",
    "detect_problem_type",
    "get_logger",
    "setup_logging",
    "suggest_target_column",
    "to_csv_bytes",
]
